package com.bingo;

import org.junit.Test;

import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.InputStream;
import java.util.HashSet;
import java.util.Iterator;

public class TestCount {
    @Test
    public void main() {
        String str = "Documentary,Short," +
                "Animation,Short," +
                "Animation,Comedy,Romance," +
                "Short," +
                "Short,Sport," +
                "Romance," +
                "Comedy,Short," +
                "Documentary,Short,Sport," +
                "News,Short," +
                "News,Short,Sport," +
                "Comedy,Documentary,Short," +
                "Drama,Short," +
                "Fantasy,Short," +
                "Horror,Short," +
                "Comedy,Horror,Short," +
                "Biography,Short," +
                "Documentary,News,Sport," +
                "Fantasy,Horror,Short," +
                "Short,War," +
                "Crime,Short," +
                "Short,Western," +
                "Comedy,Short,Sport," +
                "Comedy,Fantasy,Horror," +
                "Biography,Drama,Short," +
                "Family,Fantasy,Romance," +
                "Drama,Fantasy,Short," +
                "Adventure,Fantasy,Horror," +
                "Comedy,Romance,Short," +
                "Drama,Short,War," +
                "Comedy,Fantasy,Short," +
                "Animation,Comedy,Fantasy," +
                "Biography,Drama," +
                "Documentary,News,Short," +
                "Drama,History,Short," +
                "Crime,Drama,Short," +
                "Fantasy,Romance,Short," +
                "Drama,Horror,Short," +
                "History,Short," +
                "Adventure,Fantasy,Sci-Fi," +
                "Action,Short,Western," +
                "Action,Short," +
                "Comedy,Music,Short," +
                "Adventure,Fantasy,Short," +
                "Comedy,Family,Short," +
                "Drama,Family,Short," +
                "Crime,Drama,Mystery," +
                "News,Short,War," +
                "Animation,Fantasy,Sci-Fi," +
                "Biography,Crime,Short," +
                "Action,Crime,Family," +
                "Comedy,Fantasy,Sci-Fi," +
                "Animation,Comedy,Family," +
                "Drama,Romance,Short," +
                "Animation,Family,Fantasy," +
                "Documentary,History,Short," +
                "Biography,Crime,Drama," +
                "Adventure,Drama,Short," +
                "Drama,Music,Romance," +
                "Drama," +
                "Comedy,Drama,Short," +
                "Action,Drama,Short," +
                "Adventure,Fantasy," +
                "Animation,Fantasy,Short," +
                "Animation,Comedy,Short," +
                "Mystery,Short," +
                "Adventure,Drama,Romance," +
                "Fantasy,Sci-Fi,Short," +
                "0," +
                "Drama,Short,Western," +
                "Drama,Fantasy,Romance," +
                "Comedy," +
                "Drama,War," +
                "Romance,Short," +
                "Adventure,Comedy,Drama," +
                "Crime," +
                "Drama,History,Romance," +
                "Drama,Romance," +
                "Horror,Sci-Fi,Short," +
                "Biography,Drama,Family," +
                "Romance,Short,Western," +
                "Drama,History," +
                "Adventure,Short," +
                "History,Short,Western," +
                "Crime,History,Short," +
                "Action,Adventure,Drama," +
                "Biography,Drama,History," +
                "Sci-Fi," +
                "Adventure,Sci-Fi,Short," +
                "Adventure,Drama,Fantasy," +
                "Comedy,Crime,Short," +
                "Drama,Horror,Sci-Fi," +
                "Documentary,War," +
                "Action,Short,War," +
                "Short,Thriller," +
                "History,War," +
                "Crime,Short,Thriller," +
                "Action,Short,Thriller," +
                "Adventure," +
                "Drama,Thriller," +
                "Comedy,Drama," +
                "Comedy,Short,War," +
                "Crime,Drama," +
                "Documentary," +
                "Fantasy," +
                "Comedy,Short,Western," +
                "Biography," +
                "Action,Comedy,Short," +
                "Drama,Fantasy,Horror," +
                "Drama,Short,Thriller," +
                "Adventure,Drama," +
                "War," +
                "Crime,Thriller," +
                "Documentary,Western," +
                "Comedy,Romance," +
                "Crime,Drama,Horror," +
                "Western," +
                "Adventure,Drama,History," +
                "Drama,Fantasy," +
                "Drama,Mystery,Short," +
                "Crime,Romance,Short," +
                "Adventure,Music,Western," +
                "Drama,Horror," +
                "Action," +
                "Adventure,Horror," +
                "Horror," +
                "Comedy,Drama,Western," +
                "Drama,Mystery," +
                "Adventure,Comedy,Family," +
                "Crime,Horror,Mystery," +
                "Action,Adventure,Biography," +
                "Biography,Romance,Short," +
                "Adventure,Family,Fantasy," +
                "Adventure,Mystery," +
                "Comedy,Drama,Romance," +
                "Action,Adventure,Romance," +
                "Drama,Western," +
                "Action,Drama,Romance," +
                "Documentary,Sport," +
                "Comedy,Thriller," +
                "Drama,History,War," +
                "Drama,Sci-Fi," +
                "Drama,Romance,War," +
                "Comedy,Western," +
                "Adventure,Romance," +
                "Adventure,Short,War," +
                "Romance,Western," +
                "Adventure,Comedy," +
                "Adventure,Comedy,Western," +
                "Animation,Drama,Short," +
                "Action,Adventure,Crime," +
                "Adventure,Crime,Drama," +
                "Action,Adventure," +
                "Adventure,Romance,Western," +
                "Action,Adventure,Sci-Fi," +
                "Action,Drama," +
                "Adventure,Comedy,Romance," +
                "Biography,Western," +
                "Comedy,Crime,Drama," +
                "Comedy,Sport," +
                "Crime,Drama,Romance," +
                "Horror,Sci-Fi," +
                "Adventure,Crime," +
                "Action,Drama,War," +
                "Comedy,Drama,Mystery," +
                "Action,Comedy,Drama," +
                "Mystery," +
                "Fantasy,Romance," +
                "Comedy,Fantasy," +
                "Animation,Comedy,Drama," +
                "Drama,Family,Fantasy," +
                "Biography,Drama,Romance," +
                "Fantasy,Thriller," +
                "Comedy,Romance,Western," +
                "Adventure,Western," +
                "Drama,Horror,Mystery," +
                "Drama,History,Western," +
                "Comedy,Drama,Family," +
                "Adventure,Crime,Romance," +
                "Mystery,Thriller," +
                "Drama,Fantasy,Sci-Fi," +
                "History,Romance," +
                "Drama,Thriller,War," +
                "Drama,Family,Romance," +
                "Action,Western," +
                "Comedy,War," +
                "Animation," +
                "Musical," +
                "Crime,Drama,History," +
                "Action,Crime," +
                "Drama,Sport," +
                "Crime,Western," +
                "Comedy,Crime,Western," +
                "Drama,Romance,Western," +
                "Romance,Thriller," +
                "Drama,Horror,War," +
                "Fantasy,Horror,Mystery," +
                "Adventure,Horror,Romance," +
                "Action,Adventure,Mystery," +
                "Comedy,Drama,Sport," +
                "Action,Mystery,Thriller," +
                "Action,Comedy,Romance," +
                "Fantasy,Sci-Fi," +
                "Action,Adventure,Fantasy," +
                "Adventure,Fantasy,Mystery," +
                "Adventure,Drama,War," +
                "Comedy,Drama,Horror," +
                "Fantasy,Horror," +
                "Adventure,Sci-Fi," +
                "Biography,Comedy,Drama," +
                "Horror,Mystery," +
                "Action,Adventure,Western," +
                "Adventure,Documentary," +
                "Adventure,Drama,Western," +
                "Adventure,Fantasy,Romance," +
                "Action,Adventure,Comedy," +
                "Adventure,Comedy,Fantasy," +
                "Drama,Fantasy,Thriller," +
                "Comedy,Short,Thriller," +
                "Crime,Romance,Thriller," +
                "Action,Sport,Thriller," +
                "Drama,Romance,Sport," +
                "Crime,Mystery,Thriller," +
                "Comedy,Horror," +
                "Adventure,History," +
                "Comedy,Family," +
                "Documentary,Fantasy,Horror," +
                "Crime,Romance," +
                "Adventure,Family,Romance," +
                "Comedy,Crime," +
                "Comedy,Horror,Mystery," +
                "Animation,Documentary,Short," +
                "Drama,Musical,Short," +
                "Crime,Drama,Thriller," +
                "Drama,Horror,Romance," +
                "Action,Comedy,Sport," +
                "Music,Short," +
                "Comedy,Romance,Thriller," +
                "Biography,Music," +
                "Adventure,Family," +
                "Biography,Drama,Fantasy," +
                "History,Western," +
                "Drama,Romance,Sci-Fi," +
                "Drama,Family," +
                "Drama,Romance,Thriller," +
                "Adventure,Drama,Mystery," +
                "History,Romance,Western," +
                "Action,Sci-Fi," +
                "Sci-Fi,Short," +
                "Animation,Music,Short," +
                "Animation,Comedy,Sci-Fi," +
                "Adventure,Animation,Fantasy," +
                "Romance,Sport,Western," +
                "Drama,Mystery,Romance," +
                "Comedy,Horror,Sci-Fi," +
                "Action,Drama,Sport," +
                "Comedy,Family,Sport," +
                "Drama,Thriller,Western," +
                "Comedy,Family,Musical," +
                "Action,Drama,Sci-Fi," +
                "Comedy,Crime,Romance," +
                "Comedy,Romance,Sport," +
                "Documentary,Drama," +
                "Comedy,Drama,Fantasy," +
                "Adventure,Family,Western," +
                "Adventure,Romance,War," +
                "Action,Comedy,Crime," +
                "Comedy,Drama,War," +
                "Action,History,Romance," +
                "Action,Crime,Drama," +
                "Action,Drama,Western," +
                "Biography,History,Western," +
                "Adventure,Romance,Short," +
                "Comedy,Musical," +
                "Horror,Western," +
                "Action,Drama,Fantasy," +
                "Horror,Thriller," +
                "Adventure,Comedy,Crime," +
                "Comedy,Romance,War," +
                "Comedy,Mystery," +
                "Adventure,Drama,Thriller," +
                "Action,Crime,Romance," +
                "Drama,Music,Musical," +
                "Documentary,History," +
                "Action,Thriller," +
                "Action,Comedy," +
                "Thriller," +
                "Crime,Drama,Film-Noir," +
                "Adventure,War," +
                "Crime,Mystery," +
                "Drama,Musical," +
                "Comedy,Drama,Music," +
                "Action,Comedy,Family," +
                "Horror,Mystery,Thriller," +
                "Action,Drama,History," +
                "Action,Adventure,History," +
                "Comedy,Crime,Mystery," +
                "Drama,Music,Short," +
                "Action,Music,Romance," +
                "Crime,Musical," +
                "Drama,Musical,Romance," +
                "Comedy,Drama,Musical," +
                "Drama,Mystery,Thriller," +
                "Documentary,Music," +
                "Musical,Romance," +
                "Animation,Documentary,Music," +
                "Comedy,Musical,Romance," +
                "Adventure,Romance,Sci-Fi," +
                "Comedy,Musical,Short," +
                "Adventure,Music,Romance," +
                "Action,Drama,Thriller," +
                "Comedy,Mystery,Thriller," +
                "Mystery,Romance,Western," +
                "Action,Romance,Western," +
                "Biography,Drama,Western," +
                "Drama,Music," +
                "Crime,Drama,War," +
                "Fantasy,Musical,Short," +
                "Animation,Family,Short," +
                "Adventure,Drama,Music," +
                "Animation,Comedy,Horror," +
                "Crime,Drama,Music," +
                "Comedy,Music," +
                "Animation,Family,Romance," +
                "Comedy,Fantasy,Musical," +
                "Animation,Comedy,Music," +
                "Adventure,Fantasy,Musical," +
                "Romance,War," +
                "Animation,Family,Musical," +
                "Comedy,Music,Romance," +
                "Action,Comedy,Music," +
                "Musical,Short," +
                "Drama,Film-Noir," +
                "Action,Adventure,Music," +
                "Mystery,Romance," +
                "Comedy,Musical,Western," +
                "Adventure,Animation,Comedy," +
                "Action,Romance,Thriller," +
                "Action,Music,Western," +
                "Musical,Western," +
                "Comedy,Musical,Sport," +
                "Comedy,Mystery,Short," +
                "Adventure,Musical,Romance," +
                "Romance,War,Western," +
                "Animation,Comedy,Musical," +
                "Family,Short," +
                "Comedy,Fantasy,Romance," +
                "Adventure,Drama,Family," +
                "Adventure,Crime,Sport," +
                "Action,Adventure,Horror," +
                "Comedy,History,Musical," +
                "Comedy,Crime,Musical," +
                "Mystery,Western," +
                "Drama,Musical,Mystery," +
                "Action,Adventure,War," +
                "Biography,Drama,War," +
                "Crime,Mystery,Romance," +
                "Drama,Fantasy,Mystery," +
                "Comedy,Crime,Horror," +
                "Animation,Musical,Short," +
                "Crime,Drama,Musical," +
                "Horror,Mystery,Western," +
                "Animation,Family,Music," +
                "Adventure,Animation,Family," +
                "Adventure,Horror,Sci-Fi," +
                "Crime,Drama,Western," +
                "Adventure,Horror,Mystery," +
                "Comedy,Family,Romance," +
                "Crime,Film-Noir,Thriller," +
                "Comedy,Horror,Thriller," +
                "Animation,Short,Western," +
                "Drama,Mystery,Sci-Fi," +
                "Action,Comedy,War," +
                "Mystery,Romance,Thriller," +
                "Adventure,Documentary,Short," +
                "Musical,Romance,Short," +
                "Animation,Family,Horror," +
                "Drama,Film-Noir,Romance," +
                "History,Musical," +
                "Comedy,Sci-Fi,Short," +
                "Comedy,Musical,War," +
                "Action,Drama,Horror," +
                "Action,Mystery,Western," +
                "Action,Crime,Music," +
                "Comedy,Musical,Sci-Fi," +
                "Crime,Drama,Sport," +
                "Biography,Drama,Music," +
                "Biography,Drama,Musical," +
                "Drama,Sci-Fi,War," +
                "Crime,Horror," +
                "Music,Romance,Western," +
                "Comedy,Drama,History," +
                "Biography,Music,Romance," +
                "Action,Crime,Horror," +
                "History,Music," +
                "Comedy,Family,Fantasy," +
                "Adventure,Crime,Horror," +
                "Drama,Mystery,Sport," +
                "Action,Comedy,Western," +
                "Adventure,Drama,Horror," +
                "Crime,Sci-Fi," +
                "Adventure,Animation,Drama," +
                "Comedy,Music,Musical," +
                "Biography,Comedy," +
                "Comedy,Family,Music," +
                "Adventure,Mystery,Romance," +
                "Musical,Mystery,Romance," +
                "History," +
                "Music,Romance," +
                "Action,Romance," +
                "Crime,Musical,Romance," +
                "Action,Crime,Mystery," +
                "Comedy,Musical,Mystery," +
                "Documentary,History,War," +
                "Action,Adventure,Thriller," +
                "Comedy,Sci-Fi," +
                "Action,Drama,Mystery," +
                "Action,Mystery,Romance," +
                "Music,Musical,Short," +
                "Action,Crime,Thriller," +
                "Animation,Fantasy,Musical," +
                "Family,Musical,Romance," +
                "Action,Biography,Drama," +
                "Music,Western," +
                "Biography,Musical,Romance," +
                "Comedy,History,Romance," +
                "Family," +
                "Horror,Romance,Sci-Fi," +
                "Biography,Musical,Short," +
                "Adventure,Biography,Drama," +
                "Comedy,Crime,Music," +
                "Family,Musical,Sci-Fi," +
                "Drama,History,News," +
                "Comedy,Mystery,Romance," +
                "Adventure,Comedy,Short," +
                "Action,Crime,Western," +
                "Documentary,Short,War," +
                "Horror,Mystery,Sci-Fi," +
                "Animation,Fantasy,Horror," +
                "Adventure,History,Romance," +
                "Adventure,Comedy,Music," +
                "Adventure,History,Western," +
                "Family,Musical," +
                "Drama,War,Western," +
                "Adventure,Crime,Mystery," +
                "Adventure,Crime,Film-Noir," +
                "Comedy,Family,War," +
                "Crime,Romance,Sci-Fi," +
                "Action,Animation,Crime," +
                "Drama,History,Musical," +
                "Animation,Comedy,Crime," +
                "Horror,Sci-Fi,Thriller," +
                "Drama,Family,Musical," +
                "Adventure,Drama,Musical," +
                "Crime,Music,Mystery," +
                "Comedy,Horror,Romance," +
                "Biography,History,Romance," +
                "Action,Mystery," +
                "Musical,Romance,Western," +
                "Drama,Film-Noir,Mystery," +
                "Crime,Horror,Sci-Fi," +
                "Music,Musical,Western," +
                "Adventure,Family,Musical," +
                "Action,Adventure,Family," +
                "Documentary,Drama,History," +
                "Crime,Romance,Western," +
                "Comedy,Music,War," +
                "Drama,Musical,Western," +
                "Adventure,Crime,Sci-Fi," +
                "Adventure,Mystery,Western," +
                "Adventure,Mystery,Thriller," +
                "Adventure,Romance,Thriller," +
                "Drama,History,Music," +
                "Comedy,Music,Western," +
                "History,Musical,Romance," +
                "Mystery,Romance,Sport," +
                "Mystery,Sci-Fi," +
                "Action,Drama,Musical," +
                "Animation,Family,Sci-Fi," +
                "Animation,Drama,Family," +
                "Action,Comedy,Mystery," +
                "Drama,Music,Western," +
                "Comedy,History," +
                "Action,Drama,Music," +
                "Crime,Film-Noir,Mystery," +
                "Comedy,Family,Western," +
                "Adventure,Biography,Romance," +
                "Biography,War," +
                "History,Music,Romance," +
                "Action,Sport," +
                "Romance,Sci-Fi," +
                "Family,Fantasy," +
                "Action,Adventure,Animation," +
                "Action,Animation,Western," +
                "Action,History," +
                "Biography,Drama,Sport," +
                "Animation,Music,Romance," +
                "Documentary,Drama,News," +
                "Animation,Short,Sport," +
                "Drama,History,Mystery," +
                "Crime,Film-Noir,Romance," +
                "Action,Animation,Comedy," +
                "Music,War,Western," +
                "Comedy,Crime,Sport," +
                "Biography,Short,War," +
                "Biography,Music,Musical," +
                "Adventure,Comedy,War," +
                "Game-Show,Short," +
                "Comedy,Music,Sport," +
                "Musical,Romance,Thriller," +
                "Romance,Sport," +
                "Crime,Drama,Family," +
                "Drama,Music,Mystery," +
                "Animation,Horror,Short," +
                "Thriller,War," +
                "Biography,Comedy,Music," +
                "Drama,Family,Music," +
                "Action,Music," +
                "Drama,Fantasy,History," +
                "Biography,Documentary,Drama," +
                "Adventure,Biography,History," +
                "Romance,Thriller,War," +
                "Drama,Music,Sport," +
                "Sport,Thriller," +
                "Fantasy,Mystery," +
                "Adventure,Comedy,Mystery," +
                "Sport,Western," +
                "Drama,Film-Noir,Thriller," +
                "Comedy,Romance,Sci-Fi," +
                "Biography,Romance,Western," +
                "Comedy,Crime,Thriller," +
                "Adventure,Comedy,Sport," +
                "Sci-Fi,Western," +
                "Crime,History,Western," +
                "Musical,Romance,War," +
                "Comedy,Horror,Musical," +
                "Action,Comedy,History," +
                "Comedy,Family,Mystery," +
                "Music," +
                "Action,Animation,Drama," +
                "Biography,Comedy,Romance," +
                "Music,Short,Western," +
                "Crime,War," +
                "Animation,Romance,Short," +
                "Comedy,Thriller,Western," +
                "Documentary,Family,Music," +
                "Sport," +
                "Adventure,Comedy,Horror," +
                "Film-Noir,Mystery," +
                "Mystery,Thriller,War," +
                "Documentary,Short,Western," +
                "Action,Adventure,Musical," +
                "Adventure,Comedy,Musical," +
                "Comedy,Family,Sci-Fi," +
                "Action,Documentary," +
                "Fantasy,Musical,Romance," +
                "Adventure,Family,Sci-Fi," +
                "Comedy,Fantasy,Mystery," +
                "Adventure,Animation,Crime," +
                "Action,Crime,Musical," +
                "Action,Animation,Fantasy," +
                "Fantasy,Horror,Thriller," +
                "Biography,History," +
                "Horror,Mystery,Romance," +
                "Animation,Short,War," +
                "Animation,Documentary,Family," +
                "Adventure,Comedy,Thriller," +
                "History,Short,War," +
                "Adventure,Musical," +
                "Family,History,Short," +
                "Biography,Comedy,Musical," +
                "Animation,Comedy,Documentary," +
                "Action,Music,War," +
                "Animation,Crime,Short," +
                "Comedy,History,Music," +
                "History,Romance,Sci-Fi," +
                "War,Western," +
                "Drama,Fantasy,War," +
                "Music,Short,War," +
                "Adventure,Drama,Film-Noir," +
                "Documentary,Drama,War," +
                "Crime,War,Western," +
                "Fantasy,Musical," +
                "Film-Noir,Horror,Mystery," +
                "Action,History,War," +
                "Adventure,History,War," +
                "Adventure,Thriller," +
                "Crime,Mystery,War," +
                "Fantasy,Horror,Sci-Fi," +
                "Music,Romance,War," +
                "Fantasy,Music,Short," +
                "Documentary,Music,Short," +
                "Animation,Short,Thriller," +
                "Comedy,Music,Mystery," +
                "Comedy,Crime,Family," +
                "Action,War," +
                "Family,Western," +
                "Musical,War," +
                "Action,Crime,Film-Noir," +
                "Drama,Horror,Music," +
                "Animation,Documentary,History," +
                "Animation,Comedy,Mystery," +
                "Documentary,Drama,Short," +
                "Crime,Film-Noir,Horror," +
                "Family,Music," +
                "Horror,Music,Thriller," +
                "Adventure,Musical,War," +
                "Crime,Drama,Fantasy," +
                "Film-Noir,Romance,Thriller," +
                "Adventure,Sci-Fi,War," +
                "Comedy,Horror,Music," +
                "Adventure,Crime,Thriller," +
                "Music,Romance,Sport," +
                "Action,Comedy,Musical," +
                "Drama,Family,Sport," +
                "Action,Musical,Western," +
                "Biography,Musical," +
                "Film-Noir,Mystery,Thriller," +
                "Comedy,Thriller,War," +
                "Music,Mystery,Western," +
                "Action,History,Short," +
                "Family,Musical,Western," +
                "Adventure,Animation," +
                "Comedy,Fantasy,Music," +
                "Music,Musical,Romance," +
                "Action,Musical,Romance," +
                "Film-Noir,Thriller," +
                "Drama,Music,War," +
                "Crime,Film-Noir,Music," +
                "Music,Musical," +
                "Film-Noir,Mystery,Romance," +
                "Drama,Horror,Thriller," +
                "Comedy,Sci-Fi,War," +
                "Drama,Film-Noir,Horror," +
                "Adventure,Film-Noir,Romance," +
                "Animation,Fantasy,Romance," +
                "Biography,Music,Western," +
                "Film-Noir,Horror,Thriller," +
                "Drama,Musical,Thriller," +
                "Adventure,Comedy,History," +
                "Drama,Film-Noir,Music," +
                "Family,Game-Show," +
                "Family,Fantasy,Musical," +
                "Drama,History,Sport," +
                "Drama,Film-Noir,Sport," +
                "Fantasy,Western," +
                "Film-Noir,Mystery,Sci-Fi," +
                "Adventure,Family,Mystery," +
                "Comedy,Family,Reality-TV," +
                "Action,Biography,Crime," +
                "Drama,Family,Western," +
                "Biography,Crime,History," +
                "Comedy,Documentary," +
                "Action,Adventure,Short," +
                "Action,Drama,Film-Noir," +
                "Action,Adventure,Film-Noir," +
                "Documentary,Family,Short," +
                "Comedy,History,War," +
                "Comedy,Family,Game-Show," +
                "Family,Talk-Show," +
                "Action,Crime,Sci-Fi," +
                "Comedy,Sci-Fi,Sport," +
                "Adventure,Crime,Western," +
                "Action,Fantasy,Horror," +
                "History,Romance,Thriller," +
                "Adventure,Film-Noir," +
                "Animation,Fantasy," +
                "Biography,Documentary," +
                "Crime,Film-Noir,Sport," +
                "Drama,Sport,Thriller," +
                "Adventure,Thriller,Western," +
                "Game-Show," +
                "Action,Family,Fantasy," +
                "Thriller,Western," +
                "Drama,Mystery,War," +
                "Adventure,Drama,Sci-Fi," +
                "Sci-Fi,Thriller," +
                "Biography,Documentary,History," +
                "Drama,History,Sci-Fi," +
                "Drama,Sport,War," +
                "Action,Romance,Sport," +
                "Comedy,Game-Show," +
                "Music,Talk-Show," +
                "Crime,Film-Noir," +
                "Horror,Mystery,Short," +
                "Crime,Horror,Romance," +
                "Action,Drama,Family," +
                "Fantasy,Music,Musical," +
                "Biography,History,Music," +
                "Action,Sci-Fi,Thriller," +
                "Biography,Family,Reality-TV," +
                "News,Talk-Show," +
                "Film-Noir,Horror,Sci-Fi," +
                "Comedy,History,Short," +
                "Biography,Family,Musical," +
                "Comedy,Drama,Sci-Fi," +
                "Animation,History,Short," +
                "Animation,Musical," +
                "Sci-Fi,War," +
                "Drama,Romance,Talk-Show," +
                "Comedy,Reality-TV," +
                "Game-Show,Music," +
                "Documentary,News," +
                "Family,Sci-Fi," +
                "Animation,Family," +
                "Family,Fantasy,Music," +
                "Documentary,Drama,Romance," +
                "Drama,Sport,Western," +
                "Crime,History,Musical," +
                "Horror,Romance," +
                "Adventure,War,Western," +
                "Biography,Drama,Film-Noir," +
                "Documentary,Family," +
                "Action,Family,Sci-Fi," +
                "Adventure,Documentary,Fantasy," +
                "Drama,Fantasy,Music," +
                "Animation,Crime,Horror," +
                "Comedy,Music,Talk-Show," +
                "Action,Documentary,War," +
                "Action,Short,Sport," +
                "Action,War,Western," +
                "Action,Film-Noir,Mystery," +
                "Crime,Drama,Sci-Fi," +
                "Comedy,Fantasy,Sport," +
                "Action,Fantasy,Sci-Fi," +
                "Mystery,Sci-Fi,Thriller," +
                "Adventure,Fantasy,History," +
                "Comedy,Documentary,Music," +
                "Animation,Drama," +
                "Drama,History,Thriller," +
                "Documentary,Musical," +
                "History,War,Western," +
                "Documentary,Horror,Short," +
                "History,Thriller," +
                "Musical,Romance,Sport," +
                "Crime,Documentary,Short," +
                "Game-Show,Reality-TV," +
                "Romance,Sci-Fi,Western," +
                "Drama,Fantasy,Musical," +
                "Action,Family,Short," +
                "Biography,Documentary,Short," +
                "Adventure,Biography,Western," +
                "Comedy,Drama,Thriller," +
                "Crime,Family," +
                "Biography,Drama,Thriller," +
                "Biography,Documentary,Music," +
                "Comedy,Family,Talk-Show," +
                "Adventure,Documentary,Drama," +
                "Music,Romance,Short," +
                "Action,Romance,War," +
                "Adventure,Family,History," +
                "Adventure,Family,Short," +
                "Fantasy,Horror,Romance," +
                "Romance,Thriller,Western," +
                "Horror,Sci-Fi,Western," +
                "Drama,Sci-Fi,Thriller," +
                "Biography,Crime,Film-Noir," +
                "Crime,Horror,Thriller," +
                "Crime,Mystery,Sci-Fi," +
                "Musical,Thriller," +
                "Documentary,Drama,Sport," +
                "Documentary,Sci-Fi," +
                "Action,Biography,History," +
                "Documentary,Romance," +
                "Action,Horror,Romance," +
                "Adventure,Sci-Fi,Thriller," +
                "Animation,Comedy," +
                "Game-Show,Sport," +
                "Action,Horror,Sci-Fi," +
                "Crime,Fantasy,Horror," +
                "Family,War," +
                "Crime,History," +
                "Adventure,Comedy,Documentary," +
                "Family,History," +
                "Fantasy,Sci-Fi,Thriller," +
                "Animation,Documentary," +
                "Comedy,Sci-Fi,Thriller," +
                "Action,Horror," +
                "Action,Horror,Mystery," +
                "Adventure,History,Mystery," +
                "Comedy,Talk-Show," +
                "Talk-Show," +
                "Family,Fantasy,Horror," +
                "Musical,Mystery,Thriller," +
                "Biography,Documentary,War," +
                "Drama,Musical,Sport," +
                "Action,Fantasy," +
                "Documentary,Drama,Family," +
                "Drama,History,Horror," +
                "Adventure,Animation,Biography," +
                "Biography,Sport," +
                "Action,Animation,Short," +
                "Documentary,Horror," +
                "Comedy,Family,Horror," +
                "Fantasy,Mystery,Western," +
                "Comedy,War,Western," +
                "Drama,Family,History," +
                "Adventure,Biography,Comedy," +
                "Action,Comedy,Thriller," +
                "Fantasy,Music," +
                "Comedy,Family,History," +
                "Horror,Musical," +
                "Adventure,Fantasy,War," +
                "Family,Mystery,Romance," +
                "Documentary,History,Music," +
                "Game-Show,Romance," +
                "Biography,Crime,Thriller," +
                "Family,Sport," +
                "Adventure,Biography," +
                "Biography,Drama,Horror," +
                "Adventure,Crime,Family," +
                "Adventure,Crime,History," +
                "Comedy,Crime,Sci-Fi," +
                "Action,Animation,Family," +
                "Animation,Family,Western," +
                "Animation,Sci-Fi," +
                "Adventure,Animation,Sci-Fi," +
                "Crime,Sci-Fi,Thriller," +
                "Fantasy,Horror,Musical," +
                "Adventure,Biography,Family," +
                "Adventure,Documentary,Family," +
                "Comedy,Crime,Fantasy," +
                "Adventure,Comedy,Sci-Fi," +
                "Family,Romance," +
                "Drama,Musical,War," +
                "Comedy,Documentary,Family," +
                "Action,Animation,History," +
                "Action,Horror,Western," +
                "Adult,Drama,Mystery," +
                "Action,Comedy,Sci-Fi," +
                "Adult,Short," +
                "Adult,Drama," +
                "Documentary,History,Sport," +
                "Comedy,Documentary,Drama," +
                "Action,Thriller,Western," +
                "Adventure,Musical,Mystery," +
                "Biography,Horror," +
                "Drama,Fantasy,Sport," +
                "Adventure,Biography,Crime," +
                "Animation,Family,Sport," +
                "Adult," +
                "Adult,Fantasy,Horror," +
                "Adult,Animation,Comedy," +
                "Crime,Thriller,Western," +
                "Documentary,Music,Thriller," +
                "Adult,Documentary," +
                "Action,Thriller,War," +
                "Crime,Mystery,Western," +
                "Family,History,War," +
                "Adult,Comedy," +
                "Adventure,Family,Sport," +
                "Drama,Sci-Fi,Short," +
                "Comedy,Documentary,Sport," +
                "Fantasy,Mystery,Thriller," +
                "Biography,Documentary,Western," +
                "Biography,Romance," +
                "Adventure,Crime,Musical," +
                "Action,Adult,Western," +
                "Documentary,Drama,Music," +
                "Biography,Crime,Documentary," +
                "Adventure,Documentary,Romance," +
                "Family,History,Sci-Fi," +
                "Action,Musical,Thriller," +
                "Family,Mystery," +
                "Crime,Musical,Mystery," +
                "Animation,Family,Mystery," +
                "Family,Fantasy,Mystery," +
                "Horror,Romance,Thriller," +
                "Horror,Thriller,Western," +
                "Action,Animation,Sci-Fi," +
                "Action,Biography,Comedy," +
                "Adult,Comedy,Drama," +
                "Family,Game-Show,Mystery," +
                "Adult,Drama,Fantasy," +
                "Horror,Musical,Sci-Fi," +
                "Crime,Fantasy,Mystery," +
                "Animation,Biography,Short," +
                "Biography,Documentary,Sport," +
                "Drama,Horror,Western," +
                "Action,Comedy,Fantasy," +
                "Documentary,Drama,Fantasy," +
                "Adult,Drama,Romance," +
                "Adult,Crime,Horror," +
                "Biography,Documentary,Family," +
                "Animation,History," +
                "News," +
                "Animation,Drama,Fantasy," +
                "Action,Horror,Thriller," +
                "Documentary,Mystery," +
                "Adult,Comedy,Romance," +
                "Adult,Adventure," +
                "Adult,Horror," +
                "Music,Sci-Fi," +
                "Documentary,Family,Musical," +
                "Biography,Comedy,Western," +
                "Family,Fantasy,Sci-Fi," +
                "Documentary,History,Reality-TV," +
                "Fantasy,Mystery,Sci-Fi," +
                "Adult,Horror,Thriller," +
                "Adult,Biography,Documentary," +
                "Animation,Documentary,Musical," +
                "Adult,Fantasy," +
                "Biography,Comedy,Crime," +
                "Adult,Crime," +
                "Adult,Crime,Drama," +
                "Action,Sci-Fi,Sport," +
                "Adult,Drama,Thriller," +
                "Adult,Comedy,Horror," +
                "Fantasy,History,Horror," +
                "Comedy,News," +
                "Adult,Comedy,Fantasy," +
                "Adult,Crime,Mystery," +
                "Horror,War," +
                "Adventure,Horror,Thriller," +
                "Adult,Comedy,Musical," +
                "Adult,Drama,Horror," +
                "Action,Fantasy,Musical," +
                "Horror,Music," +
                "Adult,Romance," +
                "Biography,History,Talk-Show," +
                "Comedy,Crime,History," +
                "Family,News,Sport," +
                "Adult,Comedy,Sci-Fi," +
                "Adult,Thriller," +
                "Adventure,History,Musical," +
                "Documentary,Mystery,Sci-Fi," +
                "Family,Musical,Short," +
                "Adult,Drama,War," +
                "Biography,History,War," +
                "Adult,Drama,Musical," +
                "Adult,Mystery," +
                "Fantasy,Horror,Music," +
                "Family,Musical,Mystery," +
                "Adult,Comedy,Western," +
                "Crime,Documentary," +
                "Crime,History,Mystery," +
                "Adult,Comedy,Crime," +
                "Animation,Drama,Romance," +
                "Documentary,Reality-TV," +
                "Adult,Adventure,Comedy," +
                "Documentary,Drama,Western," +
                "Drama,Sci-Fi,Sport," +
                "Animation,Drama,Musical," +
                "Musical,Sci-Fi," +
                "Animation,Romance,Sci-Fi," +
                "Adventure,Mystery,Sci-Fi," +
                "Fantasy,History,Romance," +
                "Adult,Western," +
                "Music,News," +
                "Music,Musical,Sci-Fi," +
                "Action,Comedy,Horror," +
                "Action,Biography,Sci-Fi," +
                "Horror,Music,Short," +
                "Biography,Drama,Mystery," +
                "Crime,Horror,Music," +
                "Family,Horror,Mystery," +
                "Drama,Family,War," +
                "Reality-TV," +
                "Animation,Family,History," +
                "Comedy,Game-Show,Music," +
                "Animation,Drama,Music," +
                "Adult,Drama,History," +
                "Action,Romance,Sci-Fi," +
                "Drama,Family,Thriller," +
                "Fantasy,Romance,Thriller," +
                "Adult,Sci-Fi," +
                "Animation,Fantasy,Music," +
                "Sci-Fi,Thriller,War," +
                "Family,Reality-TV," +
                "Action,Music,Sci-Fi," +
                "Comedy,Musical,Talk-Show," +
                "Fantasy,Thriller,Western," +
                "Comedy,Music,Sci-Fi," +
                "Action,Fantasy,Romance," +
                "Drama,Horror,Musical," +
                "Crime,Sport," +
                "Animation,Biography,Drama," +
                "Action,Adult,Drama," +
                "Adult,Crime,Thriller," +
                "Animation,Biography,Documentary," +
                "Adult,Drama,Music," +
                "Biography,Sci-Fi,Thriller," +
                "Adult,Horror,Musical," +
                "Horror,Sport," +
                "Action,Fantasy,Thriller," +
                "Fantasy,Mystery,Romance," +
                "Documentary,Horror,Thriller," +
                "Action,Animation," +
                "Animation,Crime,Sci-Fi," +
                "Adult,Music," +
                "Action,Crime,Short," +
                "Adventure,Sci-Fi,Sport," +
                "History,Mystery," +
                "Biography,Crime," +
                "Action,Sci-Fi,Western," +
                "Action,Crime,Fantasy," +
                "Adventure,Fantasy,Western," +
                "Adult,Fantasy,Sci-Fi," +
                "Family,Horror," +
                "Action,Family,Romance," +
                "Action,Animation,Music," +
                "Biography,Comedy,Documentary," +
                "Documentary,Family,Fantasy," +
                "Action,Adventure,Sport," +
                "History,Romance,War," +
                "Animation,Crime,Documentary," +
                "Animation,Drama,Horror," +
                "Animation,Drama,Sci-Fi," +
                "Biography,Fantasy," +
                "Action,Animation,Horror," +
                "Comedy,Documentary,Horror," +
                "Animation,Horror,Mystery," +
                "Action,Horror,War," +
                "Animation,Crime,Drama," +
                "Documentary,Romance,Short," +
                "Crime,Documentary,Drama," +
                "Adult,Adventure,Mystery," +
                "Adventure,Drama,Sport," +
                "Animation,Drama,War," +
                "Horror,Sci-Fi,War," +
                "Action,Family," +
                "Action,History,Thriller," +
                "Animation,Biography,Comedy," +
                "Animation,Horror," +
                "Action,Game-Show,Sport," +
                "Action,Crime,Reality-TV," +
                "Drama,Music,Thriller," +
                "Action,Biography," +
                "Comedy,Mystery,Sci-Fi," +
                "Comedy,Horror,Western," +
                "Documentary,History,Romance," +
                "Family,Fantasy,Short," +
                "Adult,Comedy,Mystery," +
                "Documentary,Drama,Mystery," +
                "Adult,Adventure,Romance," +
                "Horror,Short,Thriller," +
                "Comedy,Horror,Sport," +
                "Animation,Comedy,History," +
                "Music,Thriller," +
                "Action,Adult,Adventure," +
                "Adventure,Biography,War," +
                "Adventure,Animation,Horror," +
                "Adult,Drama,Western," +
                "Comedy,Fantasy,Thriller," +
                "Crime,Reality-TV," +
                "Drama,Game-Show,Mystery," +
                "Animation,Sci-Fi,Short," +
                "Action,Fantasy,Mystery," +
                "Action,Crime,Sport," +
                "Comedy,Game-Show,News," +
                "Drama,Reality-TV," +
                "Crime,Documentary,Mystery," +
                "Family,Thriller," +
                "Biography,Horror,Mystery," +
                "Adventure,Family,Thriller," +
                "Action,Musical,Mystery," +
                "Adult,Documentary,Short," +
                "Horror,Romance,Western," +
                "Documentary,Drama,Sci-Fi," +
                "Mystery,Thriller,Western," +
                "Family,Game-Show,Music," +
                "Animation,Drama,Thriller," +
                "Action,Biography,Documentary," +
                "Biography,Comedy,Fantasy," +
                "Biography,Comedy,Thriller," +
                "Adult,Animation,Fantasy," +
                "Action,Fantasy,History," +
                "Drama,Family,Sci-Fi," +
                "Drama,Talk-Show," +
                "Comedy,News,Talk-Show," +
                "Comedy,Documentary,News," +
                "Action,Musical," +
                "Sci-Fi,Short,Thriller," +
                "Romance,Sci-Fi,Thriller," +
                "Adventure,Documentary,Sport," +
                "Adult,Adventure,Drama," +
                "Biography,Documentary,Mystery," +
                "Crime,Horror,Short," +
                "Action,Documentary,Drama," +
                "Adult,History," +
                "Mystery,Short,Thriller," +
                "Animation,Sci-Fi,Sport," +
                "Crime,Family,Mystery," +
                "Biography,Thriller," +
                "Comedy,Game-Show,Sport," +
                "Adventure,Musical,Western," +
                "Drama,Fantasy,Western," +
                "Comedy,Fantasy,History," +
                "Animation,Romance," +
                "Crime,Music,Romance," +
                "Adult,Horror,Sci-Fi," +
                "Animation,Music,Sci-Fi," +
                "Biography,Drama,Sci-Fi," +
                "Family,Short,Sport," +
                "Drama,Family,Mystery," +
                "Animation,Sci-Fi,War," +
                "Adventure,Sci-Fi,Western," +
                "Action,Adult," +
                "Documentary,Romance,War," +
                "Action,Biography,Western," +
                "Biography,History,Sport," +
                "Documentary,Thriller,War," +
                "Action,Mystery,Sci-Fi," +
                "Biography,Documentary,Romance," +
                "Drama,Family,Horror," +
                "Action,Sci-Fi,Short," +
                "Documentary,Drama,Thriller," +
                "Documentary,Horror,Music," +
                "Comedy,Family,Thriller," +
                "Comedy,Documentary,History," +
                "Action,Documentary,Sport," +
                "Comedy,Drama,Talk-Show," +
                "Game-Show,Mystery," +
                "Action,Adult,Fantasy," +
                "Adult,Fantasy,Mystery," +
                "Documentary,Horror,Sci-Fi," +
                "Adult,Biography,Comedy," +
                "Animation,Sci-Fi,Thriller," +
                "Adult,Adventure,Sci-Fi," +
                "Adult,War," +
                "Adult,Comedy,Music," +
                "Adult,Sci-Fi,Thriller," +
                "Adventure,Horror,War," +
                "Comedy,Crime,Documentary," +
                "Action,Adult,Crime," +
                "Adventure,Animation,Music," +
                "Adult,Horror,Mystery," +
                "Adult,Fantasy,Romance," +
                "Adult,Horror,Short," +
                "Action,Horror,Short," +
                "Animation,Biography,History," +
                "Adult,Crime,Romance," +
                "Action,Adult,Sci-Fi," +
                "Adult,Mystery,Thriller," +
                "Animation,Thriller," +
                "Adventure,Family,Horror," +
                "Adult,Sport," +
                "Adventure,Crime,Fantasy," +
                "Adult,Comedy,History," +
                "Action,Game-Show,Sci-Fi," +
                "Adventure,Biography,Documentary," +
                "Adventure,Documentary,News," +
                "Adventure,Crime,War," +
                "Crime,News," +
                "Fantasy,Romance,Sci-Fi," +
                "Fantasy,Short,Thriller," +
                "Biography,History,Short," +
                "Animation,Sport," +
                "Crime,Documentary,History," +
                "Comedy,Music,News," +
                "History,Horror,Short," +
                "Musical,Sport," +
                "Crime,Music,Western," +
                "Drama,Reality-TV,Talk-Show," +
                "Action,Adult,Horror," +
                "Game-Show,Music,Short," +
                "Animation,Biography,Family," +
                "Family,Fantasy,Sport," +
                "Adult,Mystery,Sci-Fi," +
                "Crime,Music," +
                "Biography,Music,Short," +
                "News,Sport," +
                "Fantasy,Music,Romance," +
                "Game-Show,Music,Talk-Show," +
                "News,Sport,Talk-Show," +
                "Adult,Romance,Short," +
                "Adventure,Animation,Romance," +
                "Adult,Comedy,Thriller," +
                "Crime,Documentary,Music," +
                "Comedy,Documentary,Romance," +
                "Crime,Documentary,War," +
                "Documentary,Music,Romance," +
                "Action,Game-Show,Reality-TV," +
                "Adult,Comedy,Documentary," +
                "Animation,Comedy,Western," +
                "Music,Short,Sport," +
                "Adventure,Music,Sci-Fi," +
                "Adventure,Animation,Short," +
                "Adult,Crime,Short," +
                "Action,Adult,Animation," +
                "Adult,Animation,Drama," +
                "Animation,Drama,Mystery," +
                "Adult,Animation," +
                "Action,Musical,War," +
                "Animation,Drama,History," +
                "Adventure,History,Thriller," +
                "Documentary,Musical,Short," +
                "Mystery,Short,Western," +
                "Documentary,Family,Sport," +
                "Animation,Horror,Sci-Fi," +
                "Drama,Short,Sport," +
                "Action,Animation,Mystery," +
                "Adult,Adventure,Fantasy," +
                "Adult,Romance,Sci-Fi," +
                "Animation,Comedy,Sport," +
                "Adult,Drama,Sport," +
                "Sport,Talk-Show," +
                "Game-Show,Short,Sport," +
                "Adult,Drama,Sci-Fi," +
                "Comedy,Documentary,Talk-Show," +
                "Biography,Comedy,Short," +
                "Horror,Music,Sci-Fi," +
                "Action,Game-Show," +
                "Animation,Crime,Fantasy," +
                "Documentary,News,War," +
                "Fantasy,Mystery,Short," +
                "Biography,Talk-Show," +
                "Action,Music,Short," +
                "Animation,Crime," +
                "Documentary,Thriller," +
                "Fantasy,History," +
                "Reality-TV,Romance," +
                "Adventure,Game-Show," +
                "Documentary,History,Mystery," +
                "Adventure,Documentary,History," +
                "Crime,Mystery,Short," +
                "Biography,Short,Western," +
                "Biography,Comedy,History," +
                "Action,Family,Thriller," +
                "Mystery,Romance,Short," +
                "Music,Sci-Fi,Thriller," +
                "Adventure,Game-Show,Reality-TV," +
                "Action,Fantasy,Western," +
                "Documentary,Reality-TV,Short," +
                "Adult,Documentary,History," +
                "Documentary,Music,Musical," +
                "Horror,Music,Musical," +
                "Action,Adult,Comedy," +
                "Comedy,Documentary,Fantasy," +
                "Documentary,Music,News," +
                "Adult,Adventure,Animation," +
                "Action,Animation,Romance," +
                "History,Music,Short," +
                "Action,Family,Sport," +
                "Action,Crime,Documentary," +
                "Adult,Romance,Thriller," +
                "Adult,Biography,Drama," +
                "Documentary,Mystery,Short," +
                "Adventure,Reality-TV," +
                "Adult,Biography," +
                "Adult,Musical," +
                "Family,Sci-Fi,Short," +
                "Adult,Romance,Western," +
                "Comedy,Reality-TV,Sci-Fi," +
                "History,Mystery,Short," +
                "Adult,Sci-Fi,Western," +
                "Adult,Crime,Talk-Show," +
                "Family,Game-Show,Sport," +
                "Musical,Short,Western," +
                "Documentary,Fantasy,Music," +
                "Documentary,Music,Mystery," +
                "Family,Sci-Fi,Thriller," +
                "Action,Documentary,Sci-Fi," +
                "Crime,Fantasy,Sci-Fi," +
                "Fantasy,Sci-Fi,Talk-Show," +
                "Documentary,Sci-Fi,Sport," +
                "Action,Animation,Sport," +
                "Crime,Fantasy,Romance," +
                "History,Mystery,Thriller," +
                "Adventure,Mystery,War," +
                "Documentary,Music,Reality-TV," +
                "Family,Music,Talk-Show," +
                "Family,Romance,Short," +
                "Comedy,History,Sci-Fi," +
                "Biography,Comedy,War," +
                "Documentary,Talk-Show," +
                "Animation,Music," +
                "Family,Game-Show,Horror," +
                "Action,Documentary,Short," +
                "Horror,Romance,War," +
                "Comedy,History,Sport," +
                "Comedy,Reality-TV,Romance," +
                "Animation,Crime,Mystery," +
                "Music,Reality-TV," +
                "Mystery,Romance,Sci-Fi," +
                "Action,Fantasy,Short," +
                "Horror,Reality-TV," +
                "Crime,Drama,Reality-TV," +
                "Drama,News,Short," +
                "Crime,Fantasy,Short," +
                "Action,Adventure,Documentary," +
                "Family,News," +
                "Adventure,Mystery,Short," +
                "Adult,Adventure,Crime," +
                "Adult,Comedy,Short," +
                "Adventure,Animation,Musical," +
                "Biography,Fantasy,Music," +
                "Adult,Comedy,Sport," +
                "History,Musical,Short," +
                "Action,Crime,History," +
                "Animation,Crime,Family," +
                "Documentary,Music,War," +
                "Animation,Fantasy,History," +
                "Action,Comedy,Documentary," +
                "Biography,Horror,Thriller," +
                "Biography,Documentary,Horror," +
                "Documentary,History,Horror," +
                "Animation,War," +
                "Game-Show,Reality-TV,Romance," +
                "Comedy,Game-Show,Romance," +
                "Adult,Talk-Show," +
                "Family,Horror,Sci-Fi," +
                "Family,History,Musical," +
                "Documentary,War,Western," +
                "Documentary,Family,History," +
                "Biography,History,Musical," +
                "Adult,Animation,Short," +
                "Crime,Short,Western," +
                "Biography,Documentary,Talk-Show," +
                "History,Reality-TV," +
                "Comedy,Documentary,Musical," +
                "Action,Music,Thriller," +
                "Action,Animation,Biography," +
                "Action,Sci-Fi,War," +
                "Adult,Mystery,Romance," +
                "Comedy,Documentary,Mystery," +
                "Comedy,Game-Show,Sci-Fi," +
                "Documentary,History,News," +
                "Comedy,Documentary,War," +
                "Adult,Comedy,Reality-TV," +
                "Music,Sport," +
                "Adult,Fantasy,Thriller," +
                "Family,News,Talk-Show," +
                "Biography,Romance,War," +
                "Animation,Mystery," +
                "Family,Game-Show,History," +
                "Action,Comedy,Reality-TV," +
                "Adult,Animation,Horror," +
                "Adventure,Family,Music," +
                "Family,Fantasy,Western," +
                "Documentary,Game-Show,News," +
                "Fantasy,Musical,Sci-Fi," +
                "Adventure,Game-Show,Mystery," +
                "Comedy,Sport,Talk-Show," +
                "Documentary,Fantasy," +
                "Adventure,Fantasy,Thriller," +
                "Comedy,Musical,Thriller," +
                "Family,Reality-TV,Sport," +
                "News,Reality-TV," +
                "Adventure,Family,Game-Show," +
                "Adult,Adventure,Horror," +
                "Horror,Music,Mystery," +
                "Crime,Fantasy," +
                "Game-Show,Reality-TV,Thriller," +
                "Action,Adventure,Game-Show," +
                "Horror,Mystery,Reality-TV," +
                "Family,Game-Show,Reality-TV," +
                "Animation,Musical,Romance," +
                "Documentary,Fantasy,Short," +
                "Animation,Music,Musical," +
                "Family,Mystery,Short," +
                "Family,Game-Show,Musical," +
                "Family,Music,Musical," +
                "Family,Music,Western," +
                "Action,Documentary,Fantasy," +
                "Comedy,News,Sport," +
                "Romance,Short,War," +
                "Adventure,Horror,Music," +
                "Game-Show,Music,Reality-TV," +
                "History,Sci-Fi," +
                "Game-Show,Mystery,Reality-TV," +
                "Documentary,Drama,Musical," +
                "Documentary,Horror,Mystery," +
                "Sci-Fi,Talk-Show," +
                "Documentary,Sci-Fi,Short," +
                "Adult,Biography,Romance," +
                "Music,News,Talk-Show," +
                "Fantasy,Musical,Mystery," +
                "Action,Animation,Thriller," +
                "Animation,Drama,Sport," +
                "Documentary,Reality-TV,Thriller," +
                "Animation,Documentary,Drama," +
                "Family,Mystery,Thriller," +
                "Adult,Documentary,Music," +
                "Family,Music,Reality-TV," +
                "Documentary,Family,Talk-Show," +
                "Mystery,Sci-Fi,Short," +
                "Comedy,Music,Reality-TV," +
                "Action,Adult,Romance," +
                "Sci-Fi,Short,Western," +
                "Horror,Reality-TV,Thriller," +
                "Sci-Fi,Short,War," +
                "Action,Documentary,Music," +
                "Comedy,Documentary,Reality-TV," +
                "Action,Adult,Sport," +
                "Action,Mystery,Short," +
                "Animation,Fantasy,Mystery," +
                "Animation,Sci-Fi,Western," +
                "Documentary,Family,News," +
                "Family,Sport,Talk-Show," +
                "Action,Documentary,Family," +
                "Adventure,Documentary,War," +
                "Adult,Animation,Mystery," +
                "Crime,Horror,Musical," +
                "Adult,Animation,Romance," +
                "History,Talk-Show," +
                "Drama,Mystery,Western," +
                "Comedy,Documentary,Sci-Fi," +
                "Music,Sci-Fi,Short," +
                "Adult,Animation,Thriller," +
                "Drama,News,Talk-Show," +
                "Comedy,Horror,Talk-Show," +
                "Horror,Musical,Short," +
                "Family,News,Short," +
                "Biography,Reality-TV,Talk-Show," +
                "Documentary,Game-Show," +
                "Documentary,Fantasy,Sci-Fi," +
                "Comedy,Documentary,Thriller," +
                "Action,Family,Horror," +
                "Musical,Sci-Fi,Thriller," +
                "Drama,Music,Sci-Fi," +
                "Adventure,Comedy,Reality-TV," +
                "Comedy,Horror,Reality-TV," +
                "Animation,Documentary,Fantasy," +
                "Horror,Romance,Short," +
                "Action,Adventure,Reality-TV," +
                "Adventure,Crime,Short," +
                "Comedy,Game-Show,Short," +
                "Adult,Crime,Fantasy," +
                "Reality-TV,Sport," +
                "Animation,Mystery,Short," +
                "Adventure,Short,Western," +
                "History,Horror," +
                "Adventure,Musical,Short," +
                "Crime,Documentary,Thriller," +
                "Adult,Horror,Romance," +
                "Biography,Documentary,Musical," +
                "Family,Short,Western," +
                "Comedy,Drama,Game-Show," +
                "Action,Comedy,Game-Show," +
                "Action,Adult,Thriller," +
                "Drama,Reality-TV,Romance," +
                "Action,Family,Musical," +
                "Documentary,Sport,Talk-Show," +
                "Horror,Short,Western," +
                "Biography,Crime,Horror," +
                "Action,Documentary,History," +
                "Family,Music,Short," +
                "Comedy,Game-Show,Musical," +
                "Adult,Sci-Fi,Short," +
                "Family,Music,Romance," +
                "Action,Documentary,Horror," +
                "Adult,Animation,Crime," +
                "Adult,Animation,Sci-Fi," +
                "Adventure,Animation,Documentary," +
                "Fantasy,Music,Mystery," +
                "Adventure,Family,Reality-TV," +
                "Comedy,Reality-TV,Sport," +
                "Comedy,Game-Show,Reality-TV," +
                "Documentary,Horror,War," +
                "Game-Show,Talk-Show," +
                "Reality-TV,Talk-Show," +
                "Animation,Mystery,Thriller," +
                "Documentary,Family,Romance," +
                "Music,Reality-TV,Talk-Show," +
                "Musical,Talk-Show," +
                "Game-Show,Musical," +
                "Reality-TV,Romance,Talk-Show," +
                "Action,Reality-TV," +
                "Drama,Horror,Reality-TV," +
                "Adventure,Documentary,Reality-TV," +
                "Adult,Reality-TV,Talk-Show," +
                "Crime,Documentary,Reality-TV," +
                "Action,Fantasy,War," +
                "Mystery,War," +
                "Documentary,Family,Reality-TV," +
                "Documentary,Mystery,Reality-TV," +
                "Biography,Reality-TV," +
                "Adult,Fantasy,Short," +
                "Animation,Comedy,Talk-Show," +
                "Adult,Mystery,War," +
                "Music,Mystery,Short," +
                "Documentary,News,Talk-Show," +
                "Adventure,Reality-TV,Sport," +
                "Crime,Documentary,Horror," +
                "Adventure,Reality-TV,Thriller," +
                "Animation,Biography," +
                "Game-Show,Reality-TV,Sport," +
                "Mystery,Reality-TV," +
                "Short,Thriller,Western," +
                "Documentary,History,Western," +
                "Documentary,Reality-TV,Sport," +
                "Documentary,Music,Sport," +
                "Animation,Horror,Musical," +
                "Romance,Sci-Fi,Short," +
                "Crime,Documentary,News," +
                "Adult,Fantasy,History," +
                "Documentary,History,Sci-Fi," +
                "Comedy,History,Reality-TV," +
                "Action,Adult,Short," +
                "Biography,Documentary,News," +
                "Adult,Reality-TV," +
                "Biography,Fantasy,History," +
                "Comedy,Drama,Reality-TV," +
                "Crime,Mystery,Reality-TV," +
                "Adventure,Crime,Reality-TV," +
                "Biography,Family,History," +
                "Drama,News," +
                "Animation,Fantasy,Sport," +
                "Adventure,Mystery,Sport," +
                "Short,Talk-Show," +
                "Sci-Fi,Sport," +
                "Action,Musical,Short," +
                "Family,Horror,Short," +
                "Comedy,Game-Show,Talk-Show," +
                "Animation,Horror,Music," +
                "Adventure,Animation,Sport," +
                "Documentary,Music,Talk-Show," +
                "Game-Show,Music,Musical," +
                "Action,Crime,War," +
                "Music,War," +
                "Animation,Comedy,War," +
                "Documentary,Family,Game-Show," +
                "Action,Reality-TV,Sport," +
                "Adventure,Documentary,Mystery," +
                "Family,Mystery,Sci-Fi," +
                "Crime,Sci-Fi,Short," +
                "Fantasy,Horror,War," +
                "Adventure,Drama,Reality-TV," +
                "Animation,Documentary,Sci-Fi," +
                "Documentary,Reality-TV,War," +
                "Reality-TV,Sci-Fi," +
                "Biography,Comedy,Horror," +
                "Comedy,Documentary,Game-Show," +
                "Family,Fantasy,Game-Show," +
                "Biography,Comedy,Sci-Fi," +
                "Music,Reality-TV,Romance," +
                "Fantasy,Reality-TV," +
                "Documentary,Drama,Reality-TV," +
                "Animation,Western," +
                "Musical,Romance,Sci-Fi," +
                "Adult,Adventure,Short," +
                "Documentary,Fantasy,Romance," +
                "Adventure,Animation,Mystery," +
                "Comedy,Game-Show,Horror," +
                "Mystery,Talk-Show," +
                "Action,Biography,Sport," +
                "Crime,Documentary,Western," +
                "Biography,Family,News," +
                "Music,News,Reality-TV," +
                "Adventure,History,Sport," +
                "Adventure,Fantasy,Game-Show," +
                "Music,Sport,Talk-Show," +
                "Reality-TV,Short," +
                "Documentary,History,Thriller," +
                "Adventure,Comedy,Talk-Show," +
                "Horror,Sport,Thriller," +
                "Comedy,Reality-TV,Talk-Show," +
                "Fantasy,Sci-Fi,Sport," +
                "Adventure,Sport," +
                "Adventure,Biography,Horror," +
                "Crime,News,Talk-Show," +
                "Horror,Thriller,War," +
                "Adventure,History,Short," +
                "Comedy,Reality-TV,Short," +
                "Animation,Romance,Sport," +
                "Drama,Family,Reality-TV," +
                "Documentary,Reality-TV,Talk-Show," +
                "Biography,Mystery," +
                "Action,Adventure,News," +
                "Crime,Music,Thriller," +
                "Adventure,Fantasy,Music," +
                "Biography,News," +
                "Animation,News,Short," +
                "History,Sport," +
                "Adventure,Music," +
                "Game-Show,History,Music," +
                "Family,History,Reality-TV," +
                "Adventure,Horror,Short," +
                "Horror,Reality-TV,Short," +
                "Fantasy,Short,Western," +
                "Musical,Sci-Fi,Short," +
                "Crime,Reality-TV,Thriller," +
                "History,News,War," +
                "Horror,Short,War," +
                "Fantasy,History,Short," +
                "Family,Reality-TV,Short," +
                "Family,Romance,Sport," +
                "Crime,Family,Romance," +
                "Action,Fantasy,Game-Show," +
                "Drama,Mystery,Reality-TV," +
                "Adventure,Animation,History," +
                "Animation,History,War," +
                "Documentary,News,Reality-TV," +
                "Drama,Reality-TV,Sport," +
                "Drama,Game-Show," +
                "Action,History,Mystery," +
                "Animation,Family,Game-Show," +
                "Animation,Comedy,Game-Show," +
                "History,News,Talk-Show," +
                "Fantasy,Music,Sci-Fi," +
                "Animation,Sport,Thriller," +
                "Documentary,Family,Mystery," +
                "Action,Fantasy,Sport," +
                "Crime,Thriller,War," +
                "Mystery,Reality-TV,Sci-Fi," +
                "Crime,Fantasy,Thriller," +
                "Drama,Family,Talk-Show," +
                "Family,History,Sport," +
                "Crime,Musical,Short," +
                "Animation,Mystery,Sci-Fi," +
                "Animation,Crime,Music," +
                "News,Reality-TV,Sport," +
                "Family,Game-Show,Talk-Show," +
                "News,Sport,War," +
                "Adventure,Short,Sport," +
                "Documentary,Horror,Reality-TV," +
                "History,Horror,Thriller," +
                "Comedy,Crime,Reality-TV," +
                "Action,Romance,Short," +
                "History,News," +
                "Fantasy,Reality-TV,Sci-Fi," +
                "Biography,Fantasy,Horror," +
                "Family,Reality-TV,Talk-Show," +
                "Music,Mystery,Thriller," +
                "Adult,Music,Romance," +
                "Crime,Fantasy,History," +
                "Animation,Game-Show," +
                "Musical,Reality-TV," +
                "Biography,Documentary,Sci-Fi," +
                "Biography,History,Mystery," +
                "Drama,Horror,Sport," +
                "Short,Sport,Western," +
                "Comedy,Mystery,Sport," +
                "History,News,Short," +
                "Crime,Sport,Thriller," +
                "Action,Documentary,Reality-TV," +
                "Biography,Documentary,Fantasy," +
                "Documentary,Musical,Romance," +
                "Documentary,Fantasy,Sport," +
                "Crime,Documentary,Family," +
                "Animation,Biography,Crime," +
                "History,Horror,Romance," +
                "Adventure,Family,War," +
                "Family,Music,Mystery," +
                "Drama,Talk-Show,War," +
                "Action,Family,Western," +
                "History,Reality-TV,War," +
                "Short,Thriller,War," +
                "Adventure,Reality-TV,Sci-Fi," +
                "Documentary,Mystery,Sport," +
                "Action,Game-Show,History," +
                "Documentary,Drama,Horror," +
                "Musical,Short,Thriller," +
                "Crime,Drama,News," +
                "Adult,Animation,Documentary," +
                "History,Sci-Fi,Thriller," +
                "Music,Mystery,Romance," +
                "History,Short,Thriller," +
                "Comedy,News,Reality-TV," +
                "Drama,Music,Reality-TV," +
                "Horror,Musical,Mystery," +
                "Drama,Music,Talk-Show," +
                "Mystery,Reality-TV,Talk-Show," +
                "Biography,Drama,Reality-TV," +
                "Action,Biography,Game-Show," +
                "Comedy,Game-Show,History," +
                "Biography,Family," +
                "Documentary,Short,Thriller," +
                "Biography,Music,Reality-TV," +
                "Biography,Crime,Mystery," +
                "Biography,Reality-TV,Short," +
                "Comedy,Music,Thriller," +
                "Family,Musical,Reality-TV," +
                "Crime,History,Thriller," +
                "Family,Music,Sport," +
                "Adventure,History,Sci-Fi," +
                "Fantasy,Short,War," +
                "Animation,Horror,War," +
                "Family,Fantasy,History," +
                "Romance,Short,Thriller," +
                "Animation,Comedy,News," +
                "Action,Sport,Talk-Show," +
                "Adult,Drama,Short," +
                "Adventure,Crime,Documentary," +
                "Animation,Documentary,News," +
                "Adventure,Documentary,Music," +
                "Documentary,Sport,War," +
                "Adventure,Documentary,Western," +
                "Biography,Comedy,Family," +
                "Biography,News,Talk-Show," +
                "Comedy,History,Talk-Show," +
                "Documentary,Family,War," +
                "Adventure,Short,Thriller," +
                "History,Romance,Short," +
                "Biography,Documentary,Reality-TV," +
                "Biography,Family,Short," +
                "Comedy,Drama,News," +
                "Adventure,Horror,Western," +
                "History,Horror,Mystery," +
                "Biography,Fantasy,Short," +
                "Drama,News,War," +
                "Comedy,Crime,Game-Show," +
                "Music,Mystery," +
                "Action,Biography,Short," +
                "Crime,Music,Musical," +
                "Comedy,News,Short," +
                "Action,Fantasy,Music," +
                "Comedy,Short,Talk-Show," +
                "Animation,Biography,Music," +
                "Fantasy,History,Music," +
                "Animation,Documentary,War," +
                "Crime,News,Thriller," +
                "Biography,Crime,Romance," +
                "Action,History,Horror," +
                "Animation,History,Musical," +
                "Drama,Musical,Sci-Fi," +
                "Animation,Horror,Thriller," +
                "Adventure,Crime,News," +
                "Biography,Comedy,News," +
                "Animation,History,Horror," +
                "Action,News,Sport," +
                "Game-Show,Romance,Talk-Show," +
                "Action,Comedy,News," +
                "Biography,History,Sci-Fi," +
                "Action,Drama,News," +
                "Horror,Talk-Show," +
                "Biography,Horror,Music," +
                "Adventure,Comedy,Game-Show," +
                "Documentary,Horror,News," +
                "Crime,News,Short," +
                "Action,Drama,Reality-TV," +
                "Biography,History,Thriller," +
                "Action,Family,Mystery," +
                "Drama,Family,News," +
                "History,Thriller,War," +
                "News,Romance," +
                "Biography,Comedy,Reality-TV," +
                "Family,Musical,Sport," +
                "Biography,Family,Mystery," +
                "Biography,Horror,Sci-Fi," +
                "Musical,Mystery,Short," +
                "Adventure,Music,Short," +
                "Action,Documentary,News," +
                "Action,Animation,Documentary," +
                "Documentary,Mystery,Thriller," +
                "Horror,Reality-TV,Sci-Fi," +
                "Biography,Family,Music," +
                "Animation,Musical,Sci-Fi," +
                "Comedy,History,Mystery," +
                "Action,Family,Music," +
                "Crime,Family,Music," +
                "Family,Music,News," +
                "Action,News," +
                "Documentary,Fantasy,History," +
                "Adventure,Romance,Sport," +
                "News,Sci-Fi," +
                "Comedy,News,Sci-Fi," +
                "Documentary,Game-Show,History," +
                "Mystery,Sci-Fi,Talk-Show," +
                "Drama,Sci-Fi,Western," +
                "Animation,Documentary,Talk-Show," +
                "Action,Adult,War," +
                "Drama,News,Romance," +
                "History,Horror,Music," +
                "Crime,Music,Short," +
                "Documentary,Short,Talk-Show," +
                "Comedy,Sci-Fi,Talk-Show," +
                "Comedy,Horror,News," +
                "Family,Horror,Thriller," +
                "Action,Adult,History," +
                "Action,Horror,Reality-TV," +
                "Mystery,Short,War," +
                "Action,History,Sci-Fi," +
                "Animation,Biography,News," +
                "Animation,Documentary,Horror," +
                "Animation,Biography,Fantasy," +
                "Action,Family,Game-Show," +
                "Action,Horror,Sport," +
                "Adult,Mystery,Short," +
                "Action,History,Reality-TV," +
                "Documentary,Mystery,News," +
                "Documentary,Sport,Western," +
                "Crime,Family,Thriller," +
                "Fantasy,History,Mystery," +
                "Biography,Family,Horror," +
                "Mystery,News,Reality-TV," +
                "Documentary,News,Thriller," +
                "Action,Sport,War," +
                "Drama,Fantasy,News," +
                "Fantasy,History,Sci-Fi," +
                "Comedy,Documentary,Western," +
                "Animation,History,News," +
                "Documentary,Family,Western," +
                "Mystery,Short,Sport," +
                "Adventure,Musical,Sci-Fi," +
                "Biography,Family,Fantasy," +
                "Family,History,News," +
                "Documentary,Musical,Mystery," +
                "Drama,News,Thriller," +
                "History,Short,Sport," +
                "Action,Music,Musical," +
                "Music,Short,Thriller," +
                "Action,Biography,Fantasy," +
                "Documentary,News,Romance," +
                "Action,News,Talk-Show," +
                "Comedy,Crime,News," +
                "Animation,Fantasy,Thriller," +
                "Adventure,Fantasy,Reality-TV," +
                "Biography,Family,Sport," +
                "Documentary,History,Musical," +
                "Family,News,Reality-TV," +
                "History,Mystery,Sci-Fi," +
                "Action,Musical,Sci-Fi," +
                "Adult,Documentary,Horror," +
                "Family,Horror,Romance," +
                "Music,Musical,Talk-Show," +
                "Crime,Musical,Thriller," +
                "Crime,Documentary,Game-Show," +
                "Animation,Biography,Sci-Fi," +
                "Animation,Documentary,Mystery," +
                "Drama,News,Reality-TV," +
                "Documentary,History,Talk-Show," +
                "Music,Mystery,Sci-Fi," +
                "Biography,Sci-Fi," +
                "Documentary,Horror,Romance," +
                "Comedy,Sport,Western," +
                "Drama,Reality-TV,Sci-Fi," +
                "Comedy,Sci-Fi,Western," +
                "Action,Biography,Thriller," +
                "Action,Documentary,Thriller," +
                "Comedy,History,Horror," +
                "Comedy,Musical,News," +
                "Reality-TV,Sport,Talk-Show," +
                "News,Reality-TV,Talk-Show," +
                "Comedy,History,News," +
                "Animation,Music,Mystery," +
                "Animation,Talk-Show," +
                "Animation,History,Music," +
                "Biography,Documentary,Thriller," +
                "News,Sci-Fi,Talk-Show," +
                "Action,Animation,Musical," +
                "Drama,Reality-TV,War," +
                "Adventure,Biography,Fantasy," +
                "Biography,History,News," +
                "Animation,Horror,Romance," +
                "History,Horror,Musical," +
                "History,Reality-TV,Thriller," +
                "History,Sci-Fi,Short," +
                "Crime,Family,Short," +
                "Music,News,Short," +
                "Romance,Short,Sport," +
                "Drama,Mystery,News," +
                "Documentary,Talk-Show,War," +
                "Comedy,Horror,War," +
                "Animation,History,Romance," +
                "Drama,Music,News," +
                "Animation,News," +
                "Biography,Comedy,Talk-Show," +
                "Action,Horror,Musical," +
                "Adventure,Documentary,Sci-Fi," +
                "Adventure,Mystery,Reality-TV," +
                "Adventure,Documentary,Talk-Show," +
                "Biography,Drama,News," +
                "Game-Show,Reality-TV,Talk-Show," +
                "Adventure,Music,Mystery," +
                "Action,Crime,News," +
                "Fantasy,Game-Show,Short," +
                "Fantasy,Game-Show,Horror," +
                "Music,Reality-TV,Short," +
                "Adventure,News," +
                "Comedy,Musical,Reality-TV," +
                "Crime,Mystery,News," +
                "Adventure,Documentary,Musical," +
                "Mystery,News," +
                "Game-Show,Horror," +
                "Documentary,Romance,Sci-Fi," +
                "Adventure,Crime,Music," +
                "Drama,Horror,News," +
                "History,Mystery,News," +
                "Action,Drama,Game-Show," +
                "Animation,History,Mystery," +
                "Crime,History,Horror," +
                "Family,Mystery,Sport," +
                "Crime,Documentary,Fantasy," +
                "Musical,Reality-TV,Talk-Show," +
                "Biography,Sport,Talk-Show," +
                "Documentary,Game-Show,Reality-TV," +
                "Animation,Mystery,Romance," +
                "Game-Show,History," +
                "Crime,Documentary,Romance," +
                "Animation,Crime,Thriller," +
                "Adventure,Biography,Short," +
                "Biography,Game-Show,Sport," +
                "News,Short,Talk-Show," +
                "Documentary,Fantasy,Musical," +
                "Sci-Fi,Short,Talk-Show," +
                "Drama,News,Sci-Fi," +
                "Comedy,Mystery,Reality-TV," +
                "Family,Fantasy,Reality-TV," +
                "News,Reality-TV,Short," +
                "Animation,Comedy,Reality-TV," +
                "Crime,Talk-Show," +
                "Action,Horror,Music," +
                "Fantasy,Talk-Show," +
                "Adult,Fantasy,Western," +
                "Biography,Crime,Reality-TV," +
                "Adventure,Reality-TV,Romance," +
                "Crime,Documentary,Sport," +
                "Comedy,Sport,Thriller," +
                "Game-Show,Horror,Reality-TV," +
                "Horror,News," +
                "Crime,Drama,Game-Show," +
                "Biography,Fantasy,Sci-Fi,";
        String[] str2 = str.split(",");
        HashSet<String> hs = new HashSet<String>();
        for (String s : str2) {
              hs.add(s);
        }
        Iterator<String> it = hs.iterator();
        if (it.hasNext()) {
            String aa_ = hs.toString().replace("[", "").replace("]", "");//去除相同项的字符串

            System.out.println(aa_);


        }
    }
}